<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../shared/PositiveCase.cs" Link="PositiveCase.cs" />
    <Compile Include="../../shared/BoundaryCase.cs" Link="BoundaryCase.cs" />
  </ItemGroup>

</Project>
