<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../shared/PositiveCase.cs" Link="PositiveCase.cs" />
    <Compile Include="../../shared/BoundaryCase.cs" Link="BoundaryCase.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" PrivateAssets="all" />
  </ItemGroup>

</Project>
